/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyOtpRouteImport } from './routes/verify-otp'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PresentationRouteImport } from './routes/presentation'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ConvexBestPracticesRouteImport } from './routes/convex-best-practices'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedStudyRouteImport } from './routes/_authenticated/study'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedFastingRouteImport } from './routes/_authenticated/fasting'
import { Route as AuthenticatedDogRouteImport } from './routes/_authenticated/dog'
import { Route as AuthenticatedSelfRouteImport } from './routes/_authenticated/_self'
import { Route as AuthenticatedSelfSettingsRouteImport } from './routes/_authenticated/_self/settings'
import { Route as AuthenticatedSelfInsightsRouteImport } from './routes/_authenticated/_self/insights'
import { Route as AuthenticatedSelfHealthRouteImport } from './routes/_authenticated/_self/health'

const VerifyOtpRoute = VerifyOtpRouteImport.update({
  id: '/verify-otp',
  path: '/verify-otp',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PresentationRoute = PresentationRouteImport.update({
  id: '/presentation',
  path: '/presentation',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ConvexBestPracticesRoute = ConvexBestPracticesRouteImport.update({
  id: '/convex-best-practices',
  path: '/convex-best-practices',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStudyRoute = AuthenticatedStudyRouteImport.update({
  id: '/study',
  path: '/study',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFastingRoute = AuthenticatedFastingRouteImport.update({
  id: '/fasting',
  path: '/fasting',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDogRoute = AuthenticatedDogRouteImport.update({
  id: '/dog',
  path: '/dog',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSelfRoute = AuthenticatedSelfRouteImport.update({
  id: '/_self',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSelfSettingsRoute =
  AuthenticatedSelfSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedSelfRoute,
  } as any)
const AuthenticatedSelfInsightsRoute =
  AuthenticatedSelfInsightsRouteImport.update({
    id: '/insights',
    path: '/insights',
    getParentRoute: () => AuthenticatedSelfRoute,
  } as any)
const AuthenticatedSelfHealthRoute = AuthenticatedSelfHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => AuthenticatedSelfRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/convex-best-practices': typeof ConvexBestPracticesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/presentation': typeof PresentationRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/dog': typeof AuthenticatedDogRoute
  '/fasting': typeof AuthenticatedFastingRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/study': typeof AuthenticatedStudyRoute
  '/health': typeof AuthenticatedSelfHealthRoute
  '/insights': typeof AuthenticatedSelfInsightsRoute
  '/settings': typeof AuthenticatedSelfSettingsRoute
}
export interface FileRoutesByTo {
  '/convex-best-practices': typeof ConvexBestPracticesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/presentation': typeof PresentationRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/': typeof AuthenticatedIndexRoute
  '/dog': typeof AuthenticatedDogRoute
  '/fasting': typeof AuthenticatedFastingRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/study': typeof AuthenticatedStudyRoute
  '/health': typeof AuthenticatedSelfHealthRoute
  '/insights': typeof AuthenticatedSelfInsightsRoute
  '/settings': typeof AuthenticatedSelfSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/convex-best-practices': typeof ConvexBestPracticesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/presentation': typeof PresentationRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/_authenticated/_self': typeof AuthenticatedSelfRouteWithChildren
  '/_authenticated/dog': typeof AuthenticatedDogRoute
  '/_authenticated/fasting': typeof AuthenticatedFastingRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/study': typeof AuthenticatedStudyRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/_self/health': typeof AuthenticatedSelfHealthRoute
  '/_authenticated/_self/insights': typeof AuthenticatedSelfInsightsRoute
  '/_authenticated/_self/settings': typeof AuthenticatedSelfSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/convex-best-practices'
    | '/forgot-password'
    | '/login'
    | '/presentation'
    | '/reset-password'
    | '/signup'
    | '/verify-otp'
    | '/dog'
    | '/fasting'
    | '/profile'
    | '/study'
    | '/health'
    | '/insights'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/convex-best-practices'
    | '/forgot-password'
    | '/login'
    | '/presentation'
    | '/reset-password'
    | '/signup'
    | '/verify-otp'
    | '/'
    | '/dog'
    | '/fasting'
    | '/profile'
    | '/study'
    | '/health'
    | '/insights'
    | '/settings'
  id:
    | '__root__'
    | '/_authenticated'
    | '/convex-best-practices'
    | '/forgot-password'
    | '/login'
    | '/presentation'
    | '/reset-password'
    | '/signup'
    | '/verify-otp'
    | '/_authenticated/_self'
    | '/_authenticated/dog'
    | '/_authenticated/fasting'
    | '/_authenticated/profile'
    | '/_authenticated/study'
    | '/_authenticated/'
    | '/_authenticated/_self/health'
    | '/_authenticated/_self/insights'
    | '/_authenticated/_self/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ConvexBestPracticesRoute: typeof ConvexBestPracticesRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PresentationRoute: typeof PresentationRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  VerifyOtpRoute: typeof VerifyOtpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-otp': {
      id: '/verify-otp'
      path: '/verify-otp'
      fullPath: '/verify-otp'
      preLoaderRoute: typeof VerifyOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/presentation': {
      id: '/presentation'
      path: '/presentation'
      fullPath: '/presentation'
      preLoaderRoute: typeof PresentationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/convex-best-practices': {
      id: '/convex-best-practices'
      path: '/convex-best-practices'
      fullPath: '/convex-best-practices'
      preLoaderRoute: typeof ConvexBestPracticesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/study': {
      id: '/_authenticated/study'
      path: '/study'
      fullPath: '/study'
      preLoaderRoute: typeof AuthenticatedStudyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/fasting': {
      id: '/_authenticated/fasting'
      path: '/fasting'
      fullPath: '/fasting'
      preLoaderRoute: typeof AuthenticatedFastingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dog': {
      id: '/_authenticated/dog'
      path: '/dog'
      fullPath: '/dog'
      preLoaderRoute: typeof AuthenticatedDogRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_self': {
      id: '/_authenticated/_self'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedSelfRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_self/settings': {
      id: '/_authenticated/_self/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSelfSettingsRouteImport
      parentRoute: typeof AuthenticatedSelfRoute
    }
    '/_authenticated/_self/insights': {
      id: '/_authenticated/_self/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof AuthenticatedSelfInsightsRouteImport
      parentRoute: typeof AuthenticatedSelfRoute
    }
    '/_authenticated/_self/health': {
      id: '/_authenticated/_self/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof AuthenticatedSelfHealthRouteImport
      parentRoute: typeof AuthenticatedSelfRoute
    }
  }
}

interface AuthenticatedSelfRouteChildren {
  AuthenticatedSelfHealthRoute: typeof AuthenticatedSelfHealthRoute
  AuthenticatedSelfInsightsRoute: typeof AuthenticatedSelfInsightsRoute
  AuthenticatedSelfSettingsRoute: typeof AuthenticatedSelfSettingsRoute
}

const AuthenticatedSelfRouteChildren: AuthenticatedSelfRouteChildren = {
  AuthenticatedSelfHealthRoute: AuthenticatedSelfHealthRoute,
  AuthenticatedSelfInsightsRoute: AuthenticatedSelfInsightsRoute,
  AuthenticatedSelfSettingsRoute: AuthenticatedSelfSettingsRoute,
}

const AuthenticatedSelfRouteWithChildren =
  AuthenticatedSelfRoute._addFileChildren(AuthenticatedSelfRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedSelfRoute: typeof AuthenticatedSelfRouteWithChildren
  AuthenticatedDogRoute: typeof AuthenticatedDogRoute
  AuthenticatedFastingRoute: typeof AuthenticatedFastingRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedStudyRoute: typeof AuthenticatedStudyRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedSelfRoute: AuthenticatedSelfRouteWithChildren,
  AuthenticatedDogRoute: AuthenticatedDogRoute,
  AuthenticatedFastingRoute: AuthenticatedFastingRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedStudyRoute: AuthenticatedStudyRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ConvexBestPracticesRoute: ConvexBestPracticesRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PresentationRoute: PresentationRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  VerifyOtpRoute: VerifyOtpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
