/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedStudyRouteImport } from './routes/_authenticated/study'
import { Route as AuthenticatedFastingRouteImport } from './routes/_authenticated/fasting'
import { Route as AuthenticatedSelfRouteImport } from './routes/_authenticated/_self'
import { Route as AuthenticatedSelfSettingsRouteImport } from './routes/_authenticated/_self/settings'
import { Route as AuthenticatedSelfHealthRouteImport } from './routes/_authenticated/_self/health'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStudyRoute = AuthenticatedStudyRouteImport.update({
  id: '/study',
  path: '/study',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFastingRoute = AuthenticatedFastingRouteImport.update({
  id: '/fasting',
  path: '/fasting',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSelfRoute = AuthenticatedSelfRouteImport.update({
  id: '/_self',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSelfSettingsRoute =
  AuthenticatedSelfSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedSelfRoute,
  } as any)
const AuthenticatedSelfHealthRoute = AuthenticatedSelfHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => AuthenticatedSelfRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/fasting': typeof AuthenticatedFastingRoute
  '/study': typeof AuthenticatedStudyRoute
  '/health': typeof AuthenticatedSelfHealthRoute
  '/settings': typeof AuthenticatedSelfSettingsRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/': typeof AuthenticatedIndexRoute
  '/fasting': typeof AuthenticatedFastingRoute
  '/study': typeof AuthenticatedStudyRoute
  '/health': typeof AuthenticatedSelfHealthRoute
  '/settings': typeof AuthenticatedSelfSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/_self': typeof AuthenticatedSelfRouteWithChildren
  '/_authenticated/fasting': typeof AuthenticatedFastingRoute
  '/_authenticated/study': typeof AuthenticatedStudyRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/_self/health': typeof AuthenticatedSelfHealthRoute
  '/_authenticated/_self/settings': typeof AuthenticatedSelfSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/fasting'
    | '/study'
    | '/health'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/signup'
    | '/'
    | '/fasting'
    | '/study'
    | '/health'
    | '/settings'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/_authenticated/_self'
    | '/_authenticated/fasting'
    | '/_authenticated/study'
    | '/_authenticated/'
    | '/_authenticated/_self/health'
    | '/_authenticated/_self/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/study': {
      id: '/_authenticated/study'
      path: '/study'
      fullPath: '/study'
      preLoaderRoute: typeof AuthenticatedStudyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/fasting': {
      id: '/_authenticated/fasting'
      path: '/fasting'
      fullPath: '/fasting'
      preLoaderRoute: typeof AuthenticatedFastingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_self': {
      id: '/_authenticated/_self'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedSelfRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_self/settings': {
      id: '/_authenticated/_self/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSelfSettingsRouteImport
      parentRoute: typeof AuthenticatedSelfRoute
    }
    '/_authenticated/_self/health': {
      id: '/_authenticated/_self/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof AuthenticatedSelfHealthRouteImport
      parentRoute: typeof AuthenticatedSelfRoute
    }
  }
}

interface AuthenticatedSelfRouteChildren {
  AuthenticatedSelfHealthRoute: typeof AuthenticatedSelfHealthRoute
  AuthenticatedSelfSettingsRoute: typeof AuthenticatedSelfSettingsRoute
}

const AuthenticatedSelfRouteChildren: AuthenticatedSelfRouteChildren = {
  AuthenticatedSelfHealthRoute: AuthenticatedSelfHealthRoute,
  AuthenticatedSelfSettingsRoute: AuthenticatedSelfSettingsRoute,
}

const AuthenticatedSelfRouteWithChildren =
  AuthenticatedSelfRoute._addFileChildren(AuthenticatedSelfRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedSelfRoute: typeof AuthenticatedSelfRouteWithChildren
  AuthenticatedFastingRoute: typeof AuthenticatedFastingRoute
  AuthenticatedStudyRoute: typeof AuthenticatedStudyRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedSelfRoute: AuthenticatedSelfRouteWithChildren,
  AuthenticatedFastingRoute: AuthenticatedFastingRoute,
  AuthenticatedStudyRoute: AuthenticatedStudyRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
